In [4]:
import nltk 
import re
import numpy
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [5]:
def word_extraction(sentence):
    words = re.sub("[^\w]", " ",  sentence).split()
    cleaned_text = [w.lower() for w in words if w not in stopwords.words('english')]
    return cleaned_text
def tokenize(sentences):
    words = []
    for sentence in sentences:
        w = word_extraction(sentence)
        words.extend(w)
    words = sorted(list(set(words)))
    return words

In [6]:
text = "Mary and Samantha arrived at the bus station early but waited until noon for the bus"
word_extraction(text)

tokenize(word_extraction(text))

def generate_bow(allsentences):
    vocab = tokenize(allsentences)
    print("Word List for Document \n{0} \n".format(vocab))
    for sentence in allsentences:
        words = word_extraction(sentence)
        bag_vector = numpy.zeros(len(vocab))
        for w in words:
            for i,word in enumerate(vocab):
                if word == w:
                    bag_vector[i] += 1
        print("{0}\n{1}\n".format(sentence,numpy.array(bag_vector)))
        print('---------------------------------------------------')

In [7]:
generate_bow(word_extraction(text))


Word List for Document 
['arrived', 'bus', 'early', 'mary', 'noon', 'samantha', 'station', 'waited'] 

mary
[0. 0. 0. 1. 0. 0. 0. 0.]

---------------------------------------------------
samantha
[0. 0. 0. 0. 0. 1. 0. 0.]

---------------------------------------------------
arrived
[1. 0. 0. 0. 0. 0. 0. 0.]

---------------------------------------------------
bus
[0. 1. 0. 0. 0. 0. 0. 0.]

---------------------------------------------------
station
[0. 0. 0. 0. 0. 0. 1. 0.]

---------------------------------------------------
early
[0. 0. 1. 0. 0. 0. 0. 0.]

---------------------------------------------------
waited
[0. 0. 0. 0. 0. 0. 0. 1.]

---------------------------------------------------
noon
[0. 0. 0. 0. 1. 0. 0. 0.]

---------------------------------------------------
bus
[0. 1. 0. 0. 0. 0. 0. 0.]

---------------------------------------------------


In [8]:
allsentences = ["Joe waited for the train",
                "The train was late",
                "Mary and Samantha took the bus",
               "I looked for Mary and Samantha at the bus station",
                "Mary and Samantha arrived at the bus station early but waited until noon for the bus"]
generate_bow(allsentences)

Word List for Document 
['arrived', 'bus', 'early', 'i', 'joe', 'late', 'looked', 'mary', 'noon', 'samantha', 'station', 'the', 'took', 'train', 'waited'] 

Joe waited for the train
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]

---------------------------------------------------
The train was late
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0.]

---------------------------------------------------
Mary and Samantha took the bus
[0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0.]

---------------------------------------------------
I looked for Mary and Samantha at the bus station
[0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0.]

---------------------------------------------------
Mary and Samantha arrived at the bus station early but waited until noon for the bus
[1. 2. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1.]

---------------------------------------------------


In [9]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(allsentences)

for i in range(len(allsentences)) : 
    print(allsentences[i])
    print(list(X.toarray()[i]))
    
    print('---------------------------------------------------')

Joe waited for the train
[0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0]
---------------------------------------------------
The train was late
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1]
---------------------------------------------------
Mary and Samantha took the bus
[1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0]
---------------------------------------------------
I looked for Mary and Samantha at the bus station
[1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0]
---------------------------------------------------
Mary and Samantha arrived at the bus station early but waited until noon for the bus
[1, 1, 1, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 2, 0, 0, 1, 1, 0]
---------------------------------------------------


In [10]:
text = "ذهب محمد و شريف الي المدرسة هذا اليوم"
print(word_extraction(text))

print(tokenize(word_extraction(text)))
generate_bow(word_extraction(text))

['ذهب', 'محمد', 'و', 'شريف', 'الي', 'المدرسة', 'هذا', 'اليوم']
['المدرسة', 'الي', 'اليوم', 'ذهب', 'شريف', 'محمد', 'هذا', 'و']
Word List for Document 
['المدرسة', 'الي', 'اليوم', 'ذهب', 'شريف', 'محمد', 'هذا', 'و'] 

ذهب
[0. 0. 0. 1. 0. 0. 0. 0.]

---------------------------------------------------
محمد
[0. 0. 0. 0. 0. 1. 0. 0.]

---------------------------------------------------
و
[0. 0. 0. 0. 0. 0. 0. 1.]

---------------------------------------------------
شريف
[0. 0. 0. 0. 1. 0. 0. 0.]

---------------------------------------------------
الي
[0. 1. 0. 0. 0. 0. 0. 0.]

---------------------------------------------------
المدرسة
[1. 0. 0. 0. 0. 0. 0. 0.]

---------------------------------------------------
هذا
[0. 0. 0. 0. 0. 0. 1. 0.]

---------------------------------------------------
اليوم
[0. 0. 1. 0. 0. 0. 0. 0.]

---------------------------------------------------


In [12]:
allsentences = ["ذهب محمد الي الجامعة",
                "نجحت مني في الاختبار",
                "تمكن محمد من السفر هذا اليوم",
               "اعتقد ان جورج سيتصل بنا اليوم",
                "لا اظن ان الاختبار سيكون سهلا"]
generate_bow(allsentences)

Word List for Document 
['اظن', 'اعتقد', 'الاختبار', 'الجامعة', 'السفر', 'الي', 'اليوم', 'ان', 'بنا', 'تمكن', 'جورج', 'ذهب', 'سهلا', 'سيتصل', 'سيكون', 'في', 'لا', 'محمد', 'من', 'مني', 'نجحت', 'هذا'] 

ذهب محمد الي الجامعة
[0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]

---------------------------------------------------
نجحت مني في الاختبار
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0.]

---------------------------------------------------
تمكن محمد من السفر هذا اليوم
[0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1.]

---------------------------------------------------
اعتقد ان جورج سيتصل بنا اليوم
[0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]

---------------------------------------------------
لا اظن ان الاختبار سيكون سهلا
[1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0.]

---------------------------------------------------


In [13]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(allsentences)

for i in range(len(allsentences)) : 
    print(allsentences[i])
    print(list(X.toarray()[i]))
    print('---------------------------------------------------')

ذهب محمد الي الجامعة
[0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
---------------------------------------------------
نجحت مني في الاختبار
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0]
---------------------------------------------------
تمكن محمد من السفر هذا اليوم
[0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1]
---------------------------------------------------
اعتقد ان جورج سيتصل بنا اليوم
[0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
---------------------------------------------------
لا اظن ان الاختبار سيكون سهلا
[1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0]
---------------------------------------------------
